### ISSUE TITLE
Can't get past /start on linux

### ISSUE THREAD

**Issue by jgmontoya** [getumbrel/umbrel-dev#11]
Hey, I could successfully run `init` and `boot` however after that when just checking out the instance I was following the start/setup and I got CORS error when trying to either skip the _writing down of the seedphrase_ ("Note down later" button) or after going through them all to try to go to the dashboard.

This occurred when accessing both using the "umbrel-dev.local" url as well as the ip directly.

![image](https://user-images.githubusercontent.com/11434422/91783091-0270ee80-ebcd-11ea-9f42-9766a5bbe0ca.png)

**Comment by lukechilds** [comment]
I've noticed this too.

If you SSH in and run:
```
sed -i 's/DEVICE_HOST:.*/DEVICE_HOST: http:\/\/umbrel-dev.local/g' docker-compose.yml
```

That should then allow it to work via umbrel-dev.local.

This should all be done automatically, I need to investigate why it isnt:

https://github.com/getumbrel/umbrel-dev/blob/19e3946b512edcc038274fa6115b128d3e37b249/Vagrantfile#L57-L60

**Comment by jgmontoya** [comment]
It didn't work :(

**Comment by lukechilds** [comment]
Are you running the latest umbrel-dev from git? Or from the Homebrew release?

The Homebrew version is a bit out of date.

Also can you view the logs, `umbrel-dev logs`, if it's giving permission errors or if Tor keeps failing you can try:

```
sudo chown -R 1000:1000 /vagrant/getumbrel/umbrel
sudo chmod -R 700 /vagrant/getumbrel/umbrel/tor/data/*
```

**Comment by jgmontoya** [comment]
> Are you running the latest umbrel-dev from git?
Yup, running it on linux (Ubuntu 18.04)

Will try that later today and report back

**Comment by jgmontoya** [comment]
Ok here I am again

from the logs

![image](https://user-images.githubusercontent.com/11434422/92045198-f496a700-ed4d-11ea-84af-854dcae629b4.png)

> you can try:

```
sudo ./scripts/stop
sudo chown -R 1000:1000 umbrel
sudo chmod -R 700 tor/data/*
sudo NETWORK=regtest ./scripts/start 
```
(had to `cd ..` between the first and second command and then `cd umbrel` back in, just mentioning it for _completeness_ )

Aaannd...


This worked!! :tada:  



![image](https://user-images.githubusercontent.com/11434422/92045916-b306fb80-ed4f-11ea-811e-59928c672fee.png)
