### ISSUE TITLE
Refactor development environment

### ISSUE THREAD

**Issue by mayankchhabra** [getumbrel/umbrel-dev#12]
- [x] Update with the latest version of Umbrel
- [x] Fix any other bugs
- [ ] Instead of running Docker containers for dashboard, middleware and manager, run them as nodejs processes with hot-reload (dashboard supports it out of the box with `yarn serve`).

**Comment by lukechilds** [comment]
I think we should support running as both Docker containers and directly on the host with Node.js.

Rebuilding the Docker containers is very useful for testing features that change the core Umbrel repo and modify the compose file.

It's just the feedback loop is a bit slow for changes only affecting UI/manager/middleware.

It would be nice if we can toggle it with something like:

```
umbrel-dev start --docker
// or
umbrel-dev start --hot-reload
```

**Comment by mayankchhabra** [comment]
Yeah, that'd be the best of both worlds!

**Comment by mayankchhabra** [comment]
Closed by https://github.com/getumbrel/umbrel-dev/pull/9
